{"name": "Verify Client profile details are updated properly", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=101.0.4951.54)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00727413+2389011]\n\tOrdinal0 [0x006B9F61+1941345]\n\tOrdinal0 [0x005AC520+836896]\n\tOrdinal0 [0x005A0682+788098]\n\tOrdinal0 [0x005A0EB8+790200]\n\tOrdinal0 [0x005A2752+796498]\n\tOrdinal0 [0x0059C0D9+770265]\n\tOrdinal0 [0x005AD9D0+842192]\n\tOrdinal0 [0x00603AE2+1194722]\n\tOrdinal0 [0x005F3F66+1130342]\n\tOrdinal0 [0x005CE546+976198]\n\tOrdinal0 [0x005CF456+980054]\n\tGetHandleVerifier [0x008D9632+1727522]\n\tGetHandleVerifier [0x0098BA4D+2457661]\n\tGetHandleVerifier [0x007BEB81+569713]\n\tGetHandleVerifier [0x007BDD76+566118]\n\tOrdinal0 [0x006C0B2B+1968939]\n\tOrdinal0 [0x006C5988+1989000]\n\tOrdinal0 [0x006C5A75+1989237]\n\tOrdinal0 [0x006CECB1+2026673]\n\tBaseThreadInitThunk [0x7603FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77027A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77027A4E+238]\n\n", "trace": "  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\ClientDashboard.py\", line 1040, in step_impl\n    context.driver.execute_script(\"window.scrollBy(0,500)\", \"\")\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 790, in execute_script\n    return self.execute(command, {\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 400, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 236, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "When Enter text in field and click on save", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=101.0.4951.54)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00727413+2389011]\n\tOrdinal0 [0x006B9F61+1941345]\n\tOrdinal0 [0x005AC520+836896]\n\tOrdinal0 [0x005A0682+788098]\n\tOrdinal0 [0x005A0EB8+790200]\n\tOrdinal0 [0x005A2752+796498]\n\tOrdinal0 [0x0059C0D9+770265]\n\tOrdinal0 [0x005AD9D0+842192]\n\tOrdinal0 [0x00603AE2+1194722]\n\tOrdinal0 [0x005F3F66+1130342]\n\tOrdinal0 [0x005CE546+976198]\n\tOrdinal0 [0x005CF456+980054]\n\tGetHandleVerifier [0x008D9632+1727522]\n\tGetHandleVerifier [0x0098BA4D+2457661]\n\tGetHandleVerifier [0x007BEB81+569713]\n\tGetHandleVerifier [0x007BDD76+566118]\n\tOrdinal0 [0x006C0B2B+1968939]\n\tOrdinal0 [0x006C5988+1989000]\n\tOrdinal0 [0x006C5A75+1989237]\n\tOrdinal0 [0x006CECB1+2026673]\n\tBaseThreadInitThunk [0x7603FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77027A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77027A4E+238]\n\n", "trace": "  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\ClientDashboard.py\", line 1040, in step_impl\n    context.driver.execute_script(\"window.scrollBy(0,500)\", \"\")\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 790, in execute_script\n    return self.execute(command, {\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 400, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\kanaka\\pycharmprojects\\qworkspace\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 236, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1652260045178, "stop": 1652260057324}, {"name": "Then Profile should be updated and updated value should display in field", "status": "skipped", "start": 1652260057324, "stop": 1652260057324}], "start": 1652260045174, "stop": 1652260057324, "uuid": "431cc943-6457-4ff8-8138-c225c876ddce", "historyId": "fc09b315eb217158868c568cb5f796e0", "fullName": "Verify Client Dashboard: Verify Client profile details are updated properly", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Verify Client Dashboard"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}